### ISSUE TITLE
Switch to InputOTC on /auth/passcode

### ISSUE THREAD

**Issue by jonmumm** [jonmumm/KitchenCraft#18]
We have a 5 character OTP. Update the form to use the component before. Dont use a separator.

https://ui.shadcn.com/docs/components/input-otp

**Comment by azacdev** [comment]
Hi, I came across your project, KitchenCraft, on Upwork. After reviewing the associated GitHub repository, I'm impressed by the work you've done and would love to contribute to its development.

I've forked the repository and am eager to start making contributions. However, I've encountered some challenges regarding the required environment variables. Could you provide guidance on how to access these variables to run the project locally?
